---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "SG Homelab"
subtitle: "Services Übersicht"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

# Optional theme customization
theme: walkxcode

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

services:
  - name: "Medien"
    icon: "fas fa-circle-play"
    items:
      - name: "Jellyfin"
        icon: "fa-solid fa-film"
        subtitle: "Filme + Serien"
        url: "http://192.168.68.221:8096"
        target: "_blank"
      - name: "Immich"
        icon: "fa-solid fa-image"
        subtitle: "Fotos"
        url: "http://192.168.68.222:2283"
        target: "_blank"
      - name: "Audiobookshelf"
        icon: "fa-solid fa-headphones"
        subtitle: "Hörbücher + Hörspiele"
        url: "http://192.168.68.244:13378"
        target: "_blank"
      - name: "Navidrome"
        icon: "fa-solid fa-music"
        subtitle: "Musik"
        url: "http://192.168.68.246:4533"
        target: "_blank"
      - name: "Kavita"
        icon: "fa-solid fa-book"
        subtitle: "eBooks"
        url: "http://192.168.68.247:5000"
        target: "_blank"
      - name: "Lazylibrarian"
        icon: "fa-solid fa-book-open"
        subtitle: "eBooks + Hörbücher"
        url: "http://192.168.68.250:5299"
        target: "_blank"
  - name: "Tools"
    icon: "fas fa-toolbox"
    items:
      - name: "Uptime Kuma"
        icon: "fa-solid fa-heart-pulse"
        subtitle: "Monitoring + Alerts"
        url: "http://192.168.68.243:3001"
        target: "_blank"
      - name: "Paperless NGX"
        icon: "fa-solid fa-file-invoice"
        subtitle: "Dokumentenmanagement"
        url: "http://192.168.68.245:8000"
        target: "_blank"
      - name: "Authelia"
        icon: "fa-solid fa-file-shield"
        subtitle: "Authentifizierungsportal"
        url: "http://192.168.68.249:9091"
        target: "_blank"
      - name: "MeTube"
        icon: "fa-brands fa-youtube"
        subtitle: "Youtube Downloader"
        url: "http://192.168.68.251:8081"
        target: "_blank"
      - name: "Pihole 1"
        icon: "fa-solid fa-sliders"
        subtitle: "DNS + Ads Blocking"
        url: "http://192.168.68.220:80/admin"
        target: "_blank"
      - name: "Pihole 2"
        icon: "fa-solid fa-sliders"
        subtitle: "DNS + Ads Blocking"
        url: "http://192.168.68.219:80/admin"
        target: "_blank"
      - name: "Home Assistant"
        icon: "fa-solid fa-house-signal"
        subtitle: "Smart Home Steuerung"
        url: "http://homeassistant.local:8123"
        target: "_blank"
      - name: "HA Cloudflared"
        icon: "fa-brands fa-cloudflare"
        subtitle: "Cloudflare Tunnel"
        url: "http://homeassistant.local:8123/hassio/addon/9074a9fa_cloudflared/config"
        target: "_blank"
  - name: "Proxmox"
    icon: "fas fa-server"
    items:
      - name: "PVE 1"
        icon: "fas fa-server"
        subtitle: "Proxmox VE Host 1"
        url: "https://192.168.68.211:8006"
        target: "_blank"
      - name: "ProxMenux pve1"
        icon: "fas fa-terminal"
        subtitle: "Proxmox Menü Host 1"
        url: "http://192.168.68.211:8008"
        target: "_blank"
      - name: "ProxMenux pve2"
        icon: "fas fa-terminal"
        subtitle: "Proxmox Menü Host 2"
        url: "http://192.168.68.212:8008"
        target: "_blank"
      - name: "ProxMenux pve3"
        icon: "fas fa-terminal"
        subtitle: "Proxmox Menü Host 3"
        url: "http://192.168.68.213:8008"
        target: "_blank"
      - name: "ProxMenux pve4"
        icon: "fas fa-terminal"
        subtitle: "Proxmox Menü Host 4"
        url: "http://192.168.68.214:8008"
        target: "_blank"
      - name: "Pulse"
        icon: "fas fa-tachometer-alt"
        subtitle: "Monitoring Dashboard"
        url: "http://192.168.68.252:7655"
        target: "_blank"
  - name: "Kubernetes"
    icon: "fas  fa-cubes"
    items:
      - name: "ArgoCD"
        icon: "fa-solid fa-code-branch"
        subtitle: "GitOps"
        url: "https://argocd.samuelgesang.de"
        target: "_blank"
      - name: "Portainer"
        icon: "fa-solid fa-docker"
        subtitle: "Container Management"
        url: "https://portainer.samuelgesang.de"
        target: "_blank"
      - name: "Grafana"
        icon: "fa-solid fa-dashboard"
        subtitle: "Monitoring Dashboards"
        url: "https://grafana.samuelgesang.de"
        target: "_blank"
