---
# NAS Configuration
nas_ip: "192.168.68.126"

# NFS Mount Points
nfs_mounts:
  - name: "Privat"
    src: "/volume1/Privat"
    path: "/mnt/nas/Privat"
    opts: "defaults,_netdev,noatime"

  - name: "scans"
    src: "/volume1/homes"
    path: "/mnt/nas/homes"
    opts: "defaults,_netdev,noatime"

  - name: "docker"
    src: "/volume2/Docker"
    path: "/mnt/nas/Docker"
    opts: "defaults,_netdev,noatime"
